### ISSUE TITLE
Broader taxonomy resolution after distinguishing ASVs

### ISSUE THREAD

**Issue by difontaine** [AstrobioMike/AstrobioMike.github.io#24]
Hi Mike,

I noticed that you mention in a couple of places in the amplicon data section of your website that it may be possible to "go back and cluster [ASVs] into some form of OTU." Do you have any recommendations about how to do this that you would consider adding to the site or maybe can describe here? 

I am working with a temporal dataset of 18S amplicon data and have about 160 ASVs. As I continue on the data analysis path, I am thinking about various ways to broaden the taxonomy a bit to pull out larger patterns in species occurrence. I also have thought about just grouping all of the "_sp" designated ASVs into their respective genus but there are some ASVs classified as "_sp." that occur at different times (winter species) than other "_sp." ASVs so I am trying to think of other ways to cluster that would still allow me to detect temporal patterns at a broader resolution. I hope that makes sense. Also thank you so much for all of the details on this site -- I am constantly returning to refresh my memory!

Thanks,
Diana

**Comment by AstrobioMike** [comment]
Hey there, Diana! 

Thanks for the kind words :) 

And I absolutely follow what you're saying and think it's a great idea to do it based on sequence similarity rather than taxonomic groupings :) 

I unfortunately haven't actually gone through the process myself yet though, and don't have much useful help for you at the moment :/ 

But if i were doing it, i'd start with looking at [vsearch](https://github.com/torognes/vsearch#vsearch) to see how to just cluster my ASVs based on the percent ID i wanted, and would then have to iron out how to track that back to a regular count table afterwards – i don't know if there will be a straightforward way to do that already, or if it's something we'd have to workout ourselves (like getting a file connecting the new clusters to all the ASVs that were clustered together, and then summing our initial ASV count table based on which were clustered together). Sometimes [usearch](https://www.drive5.com/usearch/) has some additional convenience functionality that hasn't been implemented in it's open-source vsearch counter-part, so if i were having trouble doing it with vsearch, i might look there too. 

I think it'd be a great idea to get this on the site at some point, so thank you for bringing it up and posting a suggestion for it :) I'm just not sure when i'll be able to do that and add it :/

Sorry i can't be of more help right now! If try the above out, and you get to having a mapping file of which ASVs were clustered together but have some trouble trying to work out how to generate the new count table, I'd be happy to try to help with that for now. Feel free to post here again or email me the files (which ASVs were clustered together, and the original ASV count table) at michael.lee0517@gmail.com and i can help workout how to make the new count table :) 

Good luck!
-Mike

**Comment by AstrobioMike** [comment]
And actually i just found [this helpful thread](https://github.com/benjjneb/dada2/issues/947#issuecomment-589178796) on the dada2 github, with example code. I'm not familiar with the differences between how vsearch would cluster things vs how the process there would, but I suspect going either way would still get the job done just fine – if you want to try what they have there :)

**Comment by difontaine** [comment]
Hi Mike,

Thank you so much for these suggestions -- I actually did find that thread too a couple of days ago and tried it out with all of my initial ASVs (before I used phyloseq::tax_glom() to get just the taxonomic class I'm interested in. That didn't work so well but maybe it's because I need to do the clustering with just the ASVs I'm interested in (diatoms) so that there aren't so many ASVs to begin with...I'll give that another shot and look into the suggestions you offered. 

Thank you!
Diana

**Comment by difontaine** [comment]
Hi again Mike,

I ended up using vsearch (thank you for the suggestion!)  -- the documentation is [here](https://docs.qiime2.org/2020.8/plugins/available/vsearch/cluster-features-de-novo/) I used 0.99 for my percent identity and went from 160 ASVs down to 91 clusters based on similarity. Thanks for the help! 
Diana

**Comment by AstrobioMike** [comment]
Excellent! Thanks for sharing what you ended up doing, Diana :)

**Comment by fconstancias** [comment]
Thanks for the interesting discussion. An alternative approach could be to use lulu https://github.com/tobiasgf/lulu.

**Comment by AstrobioMike** [comment]
Thanks for sharing, @fconstancias!
