### ISSUE TITLE
De novo genome assembly 

### ISSUE THREAD

**Issue by ebervilla** [AstrobioMike/AstrobioMike.github.io#35]
Hi Mike, I hope you are doing well. 

I am new in bioinformatics. I have only one question. Could I perform the genome assembly in mac terminal using the conda environment "de_novo_example"

Thank you very much for your response

**Comment by AstrobioMike** [comment]
Hi there, @ebervilla :) 

It depends on the genome (size/complexity, and amount of data we have for it) and the assembler we are trying to use whether or not there will likely be enough memory available to do so. For the data on that tutorial with the programs used there, I was able to run them on a late 2013 Macbook Pro with 8GB of memory, so yes for that data on a mac with at least 8 GB 👍 

You did make me realize I should add a note about conda environments at the top (which is [there](https://astrobiomike.github.io/genomics/de_novo_assembly#conda-installations) now). Because sometimes installing all programs into one conda environment can be problematic or slow. That note is pasted below:

> This was initially put together with everything in one [conda](https://conda.io/docs/) environment to try to keep things simpler if we weren't familiar with conda yet. Sometimes that can be a problem if some of the programs have conflicting requirements, or it might also be really slow to install. If having trouble with the below installation, consider running through the [conda intro page](/unix/conda-intro) first, and then break the following up into separate environments and run through this page – just be sure to activate the appropriate environment before a command, and deactivate it after before switching to the next (this will make sense after going through the conda page if it sounds like confusing nonsense right now 🙂 ). It'd be good practice with conda too, which is super-helpful to become familiar with.

**Comment by ebervilla** [comment]
Thank you very much for your feedback. Happy Belly Bioinformatics is awesome!! 

Bests

**Comment by AstrobioMike** [comment]
Thanks for the kind words! 

I realized now that your question might have been broader, too. Just in case, yes all those programs are able to be installed and used on a Mac 👍 

Closing this for now. But feel free to re-open or add to it if wanted of course :)
