### ISSUE TITLE
Tutorial on Filtering Host Reads - just a thoughtNew Topic Idea

### ISSUE THREAD

**Issue by tarunaaggarwal** [AstrobioMike/AstrobioMike.github.io#41]
**What else do you think should be covered on the site?** (This can be a request for something you are or did have trouble with, or it can be a suggestion for something you're comfortable with but think will help others!)

Hi Mike - I always love browsing your tutorials for suggestions when analyzing data. So far, I have mostly worked with amplicon data, but I am now working with metagenomes. Because I couldn't separate the host (pelagic Sargassum) from its microbial associates, my DNA samples and consequently my data have both Sargassum and microbial reads. Another thing to take into account is that I do not have a host reference. I have searched for a tutorial, but nothing really fit the bill...at least not well. 

I imagine many people deal with this. Do you think a tutorial on how to separate host reads from microbes without a reference genome is in the scope of your site? 

Thank you!
Taruna

**Comment by AstrobioMike** [comment]
Hi there, Taruna!

Thanks for the kind words and the suggestion :) 

I defintely agree something like this would be great. I'm not happy with the metagenomics section in general right now, and have plans to add a large page using my current workflow, but just haven't been able to find the time. So it'd be hard for me to pull together something dedicated to this in the near future :/ 

I can throw out my thoughts if you are interested though. I think if we are totally reference-less (like no sargassum genomes at all are known, and no other closely related genomes either), I'd let the host be processed along with everything else. If we are doing an assembly-based approach, we can try to find all the Sargassum contigs after assembly (or whatever rank that enables us to delineate between it and the rest, maybe as high as eukarya if we don't expect them to be in there beyond the host). Then those contigs could serve as the host reference for the system. And we could map our reads to those contigs in order to remove them, if we wanted to go back to just reads where we've done our best to remove the host. Also, if the associated community is relatively simple, you could try binning out MAGs representative of the members, and then recruit the initial reads to just a database holding those MAGs. Another possible vein is just a kraken-based taxonomic classification of all reads and removing all that come back as eukaryotic (though that might/would probably miss a lot). 

None of those would be perfect, of course, and there are i'm sure other approaches too, but i think those are reasonable to try. I'd probably first go the route of ignoring the host, then trying to find it in the assembled contigs to remove it as best as possible, and/or trying to bin out MAGs of the microbes and then using that as my starting reference of "the community that was able to be recovered as MAGs". We could then track how representative that is of the total reads sequenced by looking at the proportion of reads that recruit to this database of just MAGs – keeping in mind that what's missing could be the host, or it could be microbes that are not represented by the recovered MAGs, and we could try to flesh that out further at that point if wanted.

Sorry i don't have anything more solid/informative to point you towards. If i remember or come across anything that would be helpful I'll def let you know :)

**Comment by tarunaaggarwal** [comment]
Hi @AstrobioMike - thank you so much for those ideas. Coincidentally, I started doing exactly what you suggested. My plan is to try out 2-3 assemblers, bin them, and then assign taxonomy. Hopefully this way I can ID the Sargassum contigs and separate them from the microbes. 

I should try Kraken too... since I'm merely a grad student, my committee will want me to exhaust all options. So it's good to try different PATHS (pun intended!). 

Thank you for your time, Mike! I really appreciate it :-)
