### ISSUE TITLE
[JOSE Review] BASH lesson

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [AstrobioMike/AstrobioMike.github.io#5]
Setup instructions use curl, but that may not be installed on all computers; 
perhaps include instructions to installing.

**Comment by AstrobioMike** [comment]
Ah, good to know. I don't use `wget` for that reason, but had thought `curl` was standard. 

Since this is supposed to be starting from absolute scratch, i don't want to put install instructions there yet as I can't put in a simple one-size-fits-all-systems line to get it installed, and getting into several different install paths (or diving into conda already) is too far off the path. And i thought of putting a link to download the data, but then it requires knowing how to put it in the right place and navigate to it at the command line, which is what this page teaches. So i didn't want to do that either. I ended up adding a note saying if your system doesn't have curl and that fails, it's probably best to work in the binder environment for now while getting used to things.
