### ISSUE TITLE
Mistake when running the protocol

### ISSUE THREAD

**Issue by XELong** [AstrobioMike/AstrobioMike.github.io#54]
**Describe the mistake, bug, or typo here:**
Bad taxrank argument. Must be among the values of rank_names(physeq) 

**Link to the page containing the issue:**
phyla_counts_tab <- otu_table(tax_glom(ASV_physeq, taxrank="Phylum"))

**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
I recently followed your tutorial R code in my computer. When I ran the above step, and got the problem. I think this question would be due to the different version of phyloseq. Yes, the Rstudio, R, and R_package are all different from those in the binder. The older version is not easy to download followed your tutorial. Could you please update the tutorial based on the latest version of Rstudio, R, and R_package? I have got a lot of questions during the study of this tutorial. Unfortunately, it is not a easy problem for me about the conflict between different versions. Thank you very much!

**Comment by AstrobioMike** [comment]
Hi there, @XELong :)

Sorry you've had some trouble. I would like to try to update things, but in the past the easy way of setting up the binder didn't have a lot of later versions available (and I didn't have the time to troubleshoot other avenues of building the binder). And I think it's important to have that self-contained environment for folks who can't or don't want to setup on their computer. 

So as soon as I can I will try to update things, but it also sounds like that particular problem you listed isn't a version problem. It's telling us that the rank "Phylum" isn't in the object. Maybe this is just a mistake in the code I have there (if you're using the tutorial data). Can you tell me what you get back if you run `rank_names(ASV_physeq)`? I suspect "Phylum" won't be in there, maybe it's lowercase?

**Comment by XELong** [comment]
Thanks for your answer! I have update the mamba environment based on your tutorial. Here is the codes:
mamba create -y -n XXXX(envs) -c conda-forge -c bioconda -c r -c defaults \
             cutadapt=4.1 r-base=4.1 rstudio-desktop r-tidyverse=1.3.2 \
             r-vegan=2.6_4 r-dendextend=1.16.0 r-viridis=0.6.2 \
             bioconductor-phyloseq=1.38.0 bioconductor-deseq2=1.34.0 bioconductor-dada2=1.22.0 \
             bioconductor-biocgenerics=0.40 bioconductor-decipher=2.22.0 bioconductor-decontam=1.14.0 \
             bioconductor-biomformat=1.22.0 r-biocmanager=1.30.18 \
             r-matrix=1.5_1 libopenblas=0.3.21
However, it also has a small problem. The problem occured in this step " filtered_out <- filterAndTrim(forward_reads, filtered_forward_reads, reverse_reads, filtered_reverse_reads, maxEE=c(2,2), rm.phix=TRUE, minLen=175, truncLen=c(250,200))". Error reports that " Error in filterAndTrim(forward_reads, filtered_forward_reads, reverse_reads,  : 
  Some input files do not exist." I don't know how to fix. Fortunately, I ran this step in the latest version of dada2 and R base. It works.

**Comment by AstrobioMike** [comment]
So that isn't a version problem either. It just means the variable holding the input reads, either the forward_reads variable or reverse_reads one, isn't holding the correct path to the reads, OR our R environment isn't in the location we think it is. That it worked when you were working with a different version was just a coincidence, and whatever the initial problem was must have been resolved while re-doing something. When hitting the problem, you could have checked by seeing what was stored in those variables, ("forward_reads" and "reverse_reads"), and checking if you are where you think you are in the R environment, with `getwd()`, and looking for the expected files with `list.files()` to ensure they are where we think they are and that it matches what's in the variables that are supposed to be pointing to them. 

It sounds like a lot of problems you're hitting are just normal growing pains of getting used to things in R that we all have to fight through :)

**Comment by XELong** [comment]
Thanks! One more questions, ls *_R1.fq | cut -f1 -d "_" > samples, what means for this code. I am not familiar with the Unix. When I used my own data to run the process. There is a problem like this "ls: cannot access '*_R1.fq': No such file or directory". I have revised the file format just like the example in the tutorial. For example, "XYK0310020_sub_R2.fq.gz,    XYK0526080_sub_R2.fq.gz,  XYK0812040_sub_R2.fq.gz,  XYK10280100_sub_R2.fq.gz, XYK0312040_sub_R1.fq.gz". Could you tell me why ? Thank you very much!

**Comment by AstrobioMike** [comment]
The details make all the difference here, and it looks like what you're typing in as having done (ls R1.fq | cut -f1 -d "" > samples), isn't matching what the error says, as it says it was looking for "_R1.fq" – with an underscore in front of R1.fq. Because this entirely depends on your location and the exact file names, it's not easy to troubleshoot this way. But going on what you posted for the file names, something like this might work if in the same folder/directory as the files:

`ls *_R1.fq.gz | cut -f 1 -d "_" > samples`

You can always check first like this and seeing what prints out:

`ls *_R1.fq.gz | cut -f 1 -d "_"`

More importantly though, if wanting to do this type of work, getting this skill set is way more valuable than getting help on one specific instance like this. So I definitely recommend going through the 5-part unix crash course :) It will get you introduced and exposed to these things 👍 

https://astrobiomike.github.io/unix/unix-intro

**Comment by XELong** [comment]
Thanks a lot!
