### ISSUE TITLE
Error in running the process in my data

### ISSUE THREAD

**Issue by XELong** [AstrobioMike/AstrobioMike.github.io#55]
**Describe the mistake, bug, or typo here:**
Error in `$<-.data.frame`(`*tmp*`, color, value = character(0)) : 
  replacement has 0 rows, data has 150

**Link to the page containing the issue:**
Line 283 sample_info_tab$color <- as.character(sample_info_tab$color)

**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
Dear AstrobioMike,
         Could you please help me to fix the above question? I have search a solution for this question. I got one answer "You need to check your variable name (column name), the reason for this problem is usually because the variable name in your function is different from the variable name (column name) in the data frame." However, I don't know how to readjust parameters in your tutorial. The column of my "sample_info_tab" including "group", "site", "Depth", and "Plant". May I use the following code to run before  this step "sample_info_tab$color <- as.character(sample_info_tab$color)". 
names = c('group') 
sample_info_tab[,names] <- sapply(sample_info_tab[,names] , factor)

Best wishes

Long

**Comment by AstrobioMike** [comment]
Hi there, @XELong :)

If you want to be able to follow the tutorial with your data, including all the things that use the color column (which is most of the plots), then you'd need to have a column called "color" sample_info_tab, and it needs to hold names of colors based on the groups you care about. You can do this outside of R if it's easier, and then just read in the new sample_info.tsv that has the color column. If you look at the tutorial example data, you can see how that column is formatted, e.g., here is peaking at the file at the command-line:

![image](https://user-images.githubusercontent.com/13923308/201815331-e1aa6f3c-3e23-4696-8080-fc5bf96322ad.png)

So you'd want to add that column, with colors based on what makes sense for your data. For example, in the tutorial it's by what's the "char" column (water = blue; glassy = black; and so on). One place you can see a list of valid R colors and their names is at this page: https://r-graph-gallery.com/42-colors-names.html

If you don't have a "color" column that holds these color names for your data, then you will need to modify the code accordingly in many places. It's not as easy as me saying what to do where, unfortunately, it'd take running through all the exact code with the data files in order to make sure all different places are set accordingly. Sorry i don't have a version without colors

hope that helps

**Comment by XELong** [comment]
Thanks your very much!
