### ISSUE TITLE
Error in # generating and visualizing the PCoA with phyloseq

### ISSUE THREAD

**Issue by XELong** [AstrobioMike/AstrobioMike.github.io#57]
**Describe the mistake, bug, or typo here:**
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'unique': argument 1 is not a vector

**Link to the page containing the issue:**
Line 337-342

**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
Dear Mike,
        I face a new problem in running this step:
this code in the tutorial, 
plot_ordination(vst_physeq, vst_pcoa, color="char") + 
    geom_point(size=1) + labs(col="type") + 
    geom_text(aes(label=rownames(sample_info_tab), hjust=0.3, vjust=-0.4)) + 
    coord_fixed(sqrt(eigen_vals[2]/eigen_vals[1])) + ggtitle("PCoA") + 
    scale_color_manual(values=unique(sample_info_tab$color[order(sample_info_tab$char)])) + 
    theme_bw() + theme(legend.position="none")
this code I have revised based on my own data,
plot_ordination(vst_physeq, vst_pcoa, color="**Plant**") + 
  geom_point(size=1) + labs(col="**group**") + 
  geom_text(aes(label=rownames(sample_info_tab), hjust=0.3, vjust=-0.4)) + 
  coord_fixed(sqrt(eigen_vals[2]/eigen_vals[1])) + ggtitle("PCoA") + 
  scale_color_manual(values=unique(sample_info_tab$color[order(sample_info_tab$char)])) + 
  theme_bw() + theme(legend.position="none")
The error message just like the above list:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'unique': argument 1 is not a vector
I don't know how to fix it. I had tried to remove the color = Plant and labs ( col=group). It still had the same error.
Could you please help me to fix this problem?

Best wishes
Long

**Comment by AstrobioMike** [comment]
Heya!

Tough to help without the code and files to reproduce exactly, but based on what you pasted in, it looks like maybe you forgot to change one spot as the `scale_color_manual(values=unique(sample_info_tab$color[order(sample_info_tab$char)]))` part still has a 'char' at the end. So maybe try this:

```
plot_ordination(vst_physeq, vst_pcoa, color="Plant") +
geom_point(size=1) + labs(col="group") +
geom_text(aes(label=rownames(sample_info_tab), hjust=0.3, vjust=-0.4)) +
coord_fixed(sqrt(eigen_vals[2]/eigen_vals[1])) + ggtitle("PCoA") +
scale_color_manual(values=unique(sample_info_tab$color[order(sample_info_tab$Plant)])) +
theme_bw() + theme(legend.position="none")
```

R is its own tricky language and an additional skillset to develop unfortunately! And the tutorial R code is pretty dense, as it's by design an amplicon tutorial and not an R tutorial. But there's a big jump from my intro to R materials available on the site up to the type of R code in that amplicon tutorial. So it's totally expected to be a tough spot of the learning curve here, keep up the good fight!

**Comment by XELong** [comment]
Thanks your very much!
