### ISSUE TITLE
Phylogenetic tree construction

### ISSUE THREAD

**Issue by XELong** [AstrobioMike/AstrobioMike.github.io#58]
Dear Mike,
      Thank you very much. I had finished the process with my own data. However, I still have tow questions. First, no phylogenetic tree constructing code in your tutorial. The phylogenetic tree is also an important part for the microbial diversity analysis. Second, how to remove the unclassified data from the datasheet and reanalysis the micriobial diversity, composition etc. Thank you very much.

Best wishes

Long

**Comment by AstrobioMike** [comment]
Terribly sorry for dropping the ball on this, Long, I lost it and didn't catch it until a new issue came in today

I'm sure you're way past this now, but just responding to have my thoughts back

I didn't include a phylogenetic analysis because i don't find that to be all that essential when working with short hyper-variable regions like the amplicon workflow page is focused on. There's nothing wrong with doing it, it's just not something i consider "core" to the standard processing/analysis. 

I can't remember if we worked out removing unclassified in some other channel we were communicating through, but it'd have to be done in specific places as needed in given code.

Sorry again for not getting back to you when you brought this up here
